In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('/home/anu/Downloads/titanic(2).csv')
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [3]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [4]:
inputs=df.drop('Survived',axis='columns')
target=df.Survived

In [5]:
dummies=pd.get_dummies(inputs.Sex)
dummies.head(3)

female  male
0       0     1
1       1     0
2       1     0

In [6]:
inputs=pd.concat([inputs,dummies],axis='columns')
inputs.head()

Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [7]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1

In [10]:

#checking any nulls in column
inputs.columns[inputs.isna().any()]


Index(['Age'], dtype='object')

In [12]:
inputs.Age=inputs.Age.fillna(inputs.Age.mean())
inputs.head()

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1
3       1  35.0  53.1000       1
4       3  35.0   8.0500       0

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(inputs,target,test_size=0.3)

In [14]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [15]:
model.fit(X_train,y_train)

GaussianNB()

In [18]:
model.score(X_test,y_test)

0.7835820895522388

In [19]:
X_test[0:10]

Pclass        Age      Fare  female
551       2  27.000000   26.0000       0
610       3  39.000000   31.2750       1
337       1  41.000000  134.5000       1
638       3  41.000000   39.6875       1
281       3  28.000000    7.8542       0
191       2  19.000000   13.0000       0
99        2  34.000000   26.0000       0
330       3  29.699118   23.2500       1
420       3  29.699118    7.8958       0
589       3  29.699118    8.0500       0

In [20]:
y_test[0:10]

551    0
610    0
337    1
638    0
281    0
191    0
99     0
330    1
420    0
589    0
Name: Survived, dtype: int64

In [21]:
model.predict(X_test[0:10])

array([0, 1, 1, 1, 0, 0, 0, 1, 0, 0])

In [22]:
model.predict_proba(X_test[:10])

array([[9.14792539e-01, 8.52074611e-02],
       [3.71786172e-01, 6.28213828e-01],
       [7.67636385e-04, 9.99232364e-01],
       [3.45660830e-01, 6.54339170e-01],
       [9.61115558e-01, 3.88844419e-02],
       [9.05913896e-01, 9.40861037e-02],
       [9.20791891e-01, 7.92081089e-02],
       [3.71607406e-01, 6.28392594e-01],
       [9.61943239e-01, 3.80567606e-02],
       [9.61966945e-01, 3.80330547e-02]])

In [23]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train,y_train,cv=5)


array([0.824     , 0.76      , 0.744     , 0.75806452, 0.77419355])